services:
    ywc.jqui_widgets.slider:
        class: YWC\JQueryUIWidgetsBundle\Form\Type\SliderType
        tags:
            - { name: form.type, alias: jqui_slider }

    ywc.jqui_widgets.autocomplete:
        class: YWC\JQueryUIWidgetsBundle\Form\Type\AutocompleteType
        tags:
            - { name: form.type, alias: jqui_autocomplete }

    ywc.jqui_widgets.cgu:
        class: YWC\JQueryUIWidgetsBundle\Form\Type\CGUType
        tags:
            - { name: form.type, alias: jqui_cgu }

