services:
    ywc.jqui_widgets.slider:
        class: YWC\JQueryUIWidgetsBundle\Form\Type\SliderType
        tags:
            - { name: form.type, alias: jqui_slider }

    ywc.jqui_widgets.autocomplete:
        class: YWC\JQueryUIWidgetsBundle\Form\Type\AutocompleteType
        arguments: ["@ywc.factory.datatransformer"]
        tags:
            - { name: form.type, alias: jqui_autocomplete }

    ywc.jqui_widgets.select2:
        class: YWC\JQueryUIWidgetsBundle\Form\Type\Select2Type
        arguments: ["@ywc.factory.datatransformer"]
        tags:
            - { name: form.type, alias: select2 }

    ywc.jqui_widgets.cgu:
        class: YWC\JQueryUIWidgetsBundle\Form\Type\CGUType
        tags:
            - { name: form.type, alias: jqui_cgu }

    ywc.jqui_widgets.datepicker:
        class: YWC\JQueryUIWidgetsBundle\Form\Type\DatePickerType
        tags:
            - { name: form.type, alias: jqui_datepicker }

    ywc.jqui_widgets.datetimepicker:
        class: YWC\JQueryUIWidgetsBundle\Form\Type\DateTimePickerType
        tags:
            - { name: form.type, alias: jqui_datetimepicker }
            
    ywc.factory.datatransformer:
        class: YWC\JQueryUIWidgetsBundle\Utils\DataTransformerFactory
        arguments: ["@doctrine.orm.entity_manager"]

